### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by maximskripnik** [drbild/tristate#6]
Please publish a new version with Scala 2.13 and play-json 2.8.1 support

Thanks in advance

**Comment by maximskripnik** [comment]
I am trying to submit a PR for this, but I have encountered an issue with cats laws satisfaction.

Here is the failing test I am looking at at the moment:

```
[info] - Tristate with Unit.monadError.monadError rethrow attempt *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (TristateTests.scala:22)
[info]     Falsified after 1 successful property evaluations.
[info]     Location: (TristateTests.scala:22)
[info]     Occurred when passed generated values (
[info]       arg0 = Unspecified
[info]     )
[info]     Label of failing property:
[info]       Expected: Unspecified
[info]   Received: Absent
```

It says that the problem is with `rethrow-attempt` tests, which validates that if you try to rethrow right after an attempt, you get the same exact value you had before you "attempted" it. Here is this law (I am upgrading to 2.0 since it's the latest stable and is cross compiled against 2.11, 2.12 and 2.13):
https://github.com/typelevel/cats/blob/v2.0.0/laws/src/main/scala/cats/laws/MonadErrorLaws.scala#L23

The issue with current `MonadError` implementation for `Tristate`, which is defined over `Unit` for error type is that raising an error there means just returning the `Absent` value:
https://github.com/drbild/tristate/blob/master/tristate-cats/src/main/scala/org/davidbild/tristate/contrib/cats/Tristate.scala#L73. Such implementation makes it impossible to rethrow `Present(Left(Unit))` value back to `Unspecified`, because there is no way for us to tell whether `attempt` was done for `Absent` or `Unspecified` value just by looking at `Unit` type.

We could make `Tristate` a weaker datatype by only providing an instance for `ApplicativeError`, which does not provide a capability to `rethrow`, unlike `MonadError`.

@drbild What do you think? I am not self-confident when it comes to FP, so I would be very thankful if you decide whether it is semantically correct for Tristate to only be applicative-error-ish rather than monad-error-ish.

Perhaps, you will find it better to reimplement the error type for `MonadError` typeclass to be not `Unit`, but something that carries the information about whether the error is about absence (`Absence`) or is about lacking specification (`Unspecified`), which in dotty would be represented as `Absence | Unspecified` and in 2.x with something custom. But in this case, new api will not be compatible with the current one.

Thank you in advance.

P.S. I assume that this happened because cats v1.0.0-MF does not have this law, which `Tristate` ended up not satisfying: https://github.com/typelevel/cats/blob/v1.0.0-MF/laws/src/main/scala/cats/laws/MonadErrorLaws.scala

**Comment by maximskripnik** [comment]
@drbild If it's convenient for you, let's continue this discussion in the https://github.com/drbild/tristate/pull/7, where I removed `MonadError` from the set of typeclass instances for `Tristate` and replaced it with `ApplicativeError` as suggested

**Comment by drbild** [comment]
I think changing to `ApplicativeError` is fine.  That's least disruptive to the current API.

Ultimately, perhaps all the error typeclasses should be dropped.  Whether both `Absent` and `Unspecified` should be considered "errors", or just `Unspecified`, is context dependent.  If we drop the error typeclasses entirely, applications can still discharge to `Option[A]` if the error behavior is desired.
